server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://bldkhdthfjfgjyxdt9vz-postgresql.services.clever-cloud.com:50013/bldkhdthfjfgjyxdt9vz
    username: usxdiwpcoi8povipxnwl
    password: Fvs2goe2MZb9ha66yZvLKQpkFnaBXl
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  flyway:
    enabled: true
    schemas: technology
    locations: classpath:db/migration
    logging:
      level:
        org.flywaydb: DEBUG
    validate-on-migrate: false
    baseline-on-migrate: true
