server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  flyway:
    enabled: true
    schemas: technology
    locations: classpath:db/migration
    logging:
      level:
        org.flywaydb: DEBUG
    validate-on-migrate: false
